// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website.Models;

#nullable disable

namespace website.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20251209064431_CreateProductsTable")]
    partial class CreateProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("website.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "/images/bed1.jpg",
                            Description = "Comfortable and stylish beds for your bedroom",
                            ImageUrl = "/images/b1.jpg",
                            Name = "Beds"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "/images/Sofas.jpg",
                            Description = "Comfortable and stylish beds for your bedroom",
                            ImageUrl = "/images/s1.jpg",
                            Name = "Sofas"
                        },
                        new
                        {
                            Id = 3,
                            BannerImageUrl = "/images/ch.jpg",
                            Description = "Elegant chairs for dining and living spaces",
                            ImageUrl = "/images/c1.jpg",
                            Name = "Chairs"
                        },
                        new
                        {
                            Id = 4,
                            BannerImageUrl = "/images/lamp.jpg",
                            Description = "Stylish lighting to brighten your home",
                            ImageUrl = "/images/l1.jpg",
                            Name = "Lamps"
                        },
                        new
                        {
                            Id = 5,
                            BannerImageUrl = "/images/mi.jpg",
                            Description = "Decorative mirrors for every room",
                            ImageUrl = "/images/m1.jpg",
                            Name = "Mirrors"
                        },
                        new
                        {
                            Id = 6,
                            BannerImageUrl = "/images/di.jpg",
                            Description = "Beautiful decor items to enhance your space",
                            ImageUrl = "/images/de1.jpg",
                            Name = "Decor Items"
                        },
                        new
                        {
                            Id = 7,
                            BannerImageUrl = "/images/dining.jpg",
                            Description = "Elegant dining tables for family meals",
                            ImageUrl = "/images/d1.jpg",
                            Name = "Dining Tables"
                        },
                        new
                        {
                            Id = 8,
                            BannerImageUrl = "/images/tab.jpg",
                            Description = "Functional tables for living and work spaces",
                            ImageUrl = "/images/t1.jpg",
                            Name = "Tables"
                        });
                });

            modelBuilder.Entity("website.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("website.Models.Product", b =>
                {
                    b.HasOne("website.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
