// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using website.Models;

#nullable disable

namespace website.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20251209064608_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("website.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "/images/bed1.jpg",
                            Description = "Comfortable and stylish beds for your bedroom",
                            ImageUrl = "/images/b1.jpg",
                            Name = "Beds"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "/images/Sofas.jpg",
                            Description = "Comfortable and stylish beds for your bedroom",
                            ImageUrl = "/images/s1.jpg",
                            Name = "Sofas"
                        },
                        new
                        {
                            Id = 3,
                            BannerImageUrl = "/images/ch.jpg",
                            Description = "Elegant chairs for dining and living spaces",
                            ImageUrl = "/images/c1.jpg",
                            Name = "Chairs"
                        },
                        new
                        {
                            Id = 4,
                            BannerImageUrl = "/images/lamp.jpg",
                            Description = "Stylish lighting to brighten your home",
                            ImageUrl = "/images/l1.jpg",
                            Name = "Lamps"
                        },
                        new
                        {
                            Id = 5,
                            BannerImageUrl = "/images/mi.jpg",
                            Description = "Decorative mirrors for every room",
                            ImageUrl = "/images/m1.jpg",
                            Name = "Mirrors"
                        },
                        new
                        {
                            Id = 6,
                            BannerImageUrl = "/images/di.jpg",
                            Description = "Beautiful decor items to enhance your space",
                            ImageUrl = "/images/de1.jpg",
                            Name = "Decor Items"
                        },
                        new
                        {
                            Id = 7,
                            BannerImageUrl = "/images/dining.jpg",
                            Description = "Elegant dining tables for family meals",
                            ImageUrl = "/images/d1.jpg",
                            Name = "Dining Tables"
                        },
                        new
                        {
                            Id = 8,
                            BannerImageUrl = "/images/tab.jpg",
                            Description = "Functional tables for living and work spaces",
                            ImageUrl = "/images/t1.jpg",
                            Name = "Tables"
                        });
                });

            modelBuilder.Entity("website.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "White",
                            Description = "Comfortable bed",
                            ImageUrl = "/images/b1.jpg",
                            IsTrending = false,
                            Name = "Bed b1",
                            Price = 35000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Green",
                            Description = "Stylish bed",
                            ImageUrl = "/images/b2.jpg",
                            IsTrending = false,
                            Name = "Bed b2",
                            Price = 40000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Color = "Beige",
                            Description = "Luxury bed",
                            ImageUrl = "/images/b3.jpg",
                            IsTrending = false,
                            Name = "Bed b3",
                            Price = 50000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Color = "Brown",
                            Description = "Modern bed",
                            ImageUrl = "/images/b4.jpg",
                            IsTrending = false,
                            Name = "Bed b4",
                            Price = 45000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Color = "White",
                            Description = "Classic bed",
                            ImageUrl = "/images/b5.jpg",
                            IsTrending = false,
                            Name = "Bed b5",
                            Price = 38000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Color = "Pink",
                            Description = "Cozy bed",
                            ImageUrl = "/images/b6.jpg",
                            IsTrending = false,
                            Name = "Bed b6",
                            Price = 42000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Color = "Grey",
                            Description = "Comfort bed",
                            ImageUrl = "/images/b7.jpg",
                            IsTrending = false,
                            Name = "Bed b7",
                            Price = 39000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Color = "White",
                            Description = "Elegant bed",
                            ImageUrl = "/images/b8.jpg",
                            IsTrending = false,
                            Name = "Bed b8",
                            Price = 46000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Color = "Grey",
                            Description = "Modern bed",
                            ImageUrl = "/images/b9.jpg",
                            IsTrending = false,
                            Name = "Bed b9",
                            Price = 47000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Color = "Beige",
                            Description = "Luxury bed",
                            ImageUrl = "/images/b10.jpg",
                            IsTrending = false,
                            Name = "Bed b10",
                            Price = 48000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Color = "Pink",
                            Description = "Classic bed",
                            ImageUrl = "/images/b11.jpg",
                            IsTrending = false,
                            Name = "Bed b11",
                            Price = 43000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Color = "Beige",
                            Description = "Stylish bed",
                            ImageUrl = "/images/b12.jpg",
                            IsTrending = false,
                            Name = "Bed b12",
                            Price = 44000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Color = "Pink",
                            Description = "Soft sofa",
                            ImageUrl = "/images/s1.jpg",
                            IsTrending = false,
                            Name = "Sofa s1",
                            Price = 25000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Color = "Blue",
                            Description = "Elegant sofa",
                            ImageUrl = "/images/s2.jpg",
                            IsTrending = false,
                            Name = "Sofa s2",
                            Price = 27000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Color = "Green",
                            Description = "Modern sofa",
                            ImageUrl = "/images/s3.jpg",
                            IsTrending = false,
                            Name = "Sofa s3",
                            Price = 30000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Color = "Black/White",
                            Description = "Stylish sofa",
                            ImageUrl = "/images/s4.jpg",
                            IsTrending = false,
                            Name = "Sofa s4",
                            Price = 32000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Color = "Beige",
                            Description = "Cozy sofa",
                            ImageUrl = "/images/s5.jpg",
                            IsTrending = false,
                            Name = "Sofa s5",
                            Price = 29000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Color = "Green",
                            Description = "Comfortable sofa",
                            ImageUrl = "/images/s6.jpg",
                            IsTrending = false,
                            Name = "Sofa s6",
                            Price = 31000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Color = "White",
                            Description = "Modern sofa",
                            ImageUrl = "/images/s7.jpg",
                            IsTrending = false,
                            Name = "Sofa s7",
                            Price = 28000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Color = "Grey",
                            Description = "Elegant sofa",
                            ImageUrl = "/images/s8.jpg",
                            IsTrending = false,
                            Name = "Sofa s8",
                            Price = 30000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Color = "Blue",
                            Description = "Stylish sofa",
                            ImageUrl = "/images/s9.jpg",
                            IsTrending = false,
                            Name = "Sofa s9",
                            Price = 33000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Color = "Purple",
                            Description = "Cozy sofa",
                            ImageUrl = "/images/s10.jpg",
                            IsTrending = false,
                            Name = "Sofa s10",
                            Price = 34000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Color = "Pink",
                            Description = "Round sofa",
                            ImageUrl = "/images/s11.jpg",
                            IsTrending = false,
                            Name = "Sofa s11",
                            Price = 35000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Color = "White",
                            Description = "Comfort sofa",
                            ImageUrl = "/images/s12.jpg",
                            IsTrending = false,
                            Name = "Sofa s12",
                            Price = 32000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Color = "Beige",
                            Description = "Luxury sofa",
                            ImageUrl = "/images/s13.jpg",
                            IsTrending = false,
                            Name = "Sofa s13",
                            Price = 36000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Color = "White",
                            Description = "Elegant chair",
                            ImageUrl = "/images/c1.jpg",
                            IsTrending = false,
                            Name = "Chair c1",
                            Price = 7000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Color = "Brown",
                            Description = "Comfort chair",
                            ImageUrl = "/images/c2.jpg",
                            IsTrending = false,
                            Name = "Chair c2",
                            Price = 7500m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Color = "Grey",
                            Description = "Stylish chair",
                            ImageUrl = "/images/c3.jpg",
                            IsTrending = false,
                            Name = "Chair c3",
                            Price = 8000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Color = "Blue",
                            Description = "Modern chair",
                            ImageUrl = "/images/c4.jpg",
                            IsTrending = false,
                            Name = "Chair c4",
                            Price = 8200m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Color = "White",
                            Description = "Round chair",
                            ImageUrl = "/images/c5.jpg",
                            IsTrending = false,
                            Name = "Chair c5",
                            Price = 8500m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Color = "Grey",
                            Description = "Unique chair",
                            ImageUrl = "/images/c6.jpg",
                            IsTrending = false,
                            Name = "Chair c6",
                            Price = 8700m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Color = "White",
                            Description = "Stylish chair",
                            ImageUrl = "/images/c7.jpg",
                            IsTrending = false,
                            Name = "Chair c7",
                            Price = 8800m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Color = "Beige",
                            Description = "Comfortable chair",
                            ImageUrl = "/images/c8.jpg",
                            IsTrending = false,
                            Name = "Chair c8",
                            Price = 9000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Color = "White",
                            Description = "Modern chair",
                            ImageUrl = "/images/c9.jpg",
                            IsTrending = false,
                            Name = "Chair c9",
                            Price = 9100m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Color = "Beige",
                            Description = "Round chair",
                            ImageUrl = "/images/c10.jpg",
                            IsTrending = false,
                            Name = "Chair c10",
                            Price = 9200m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Color = "White",
                            Description = "Stylish chair",
                            ImageUrl = "/images/c11.jpg",
                            IsTrending = false,
                            Name = "Chair c11",
                            Price = 9300m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Color = "Beige",
                            Description = "Comfort chair",
                            ImageUrl = "/images/c12.jpg",
                            IsTrending = false,
                            Name = "Chair c12",
                            Price = 9400m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 4,
                            Color = "White",
                            Description = "Modern lamp",
                            ImageUrl = "/images/l1.jpg",
                            IsTrending = false,
                            Name = "Lamp l1",
                            Price = 4500m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 4,
                            Color = "Black",
                            Description = "Table lamp",
                            ImageUrl = "/images/l2.jpg",
                            IsTrending = false,
                            Name = "Lamp l2",
                            Price = 4200m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 4,
                            Color = "Gold",
                            Description = "Classic lamp",
                            ImageUrl = "/images/l3.jpg",
                            IsTrending = false,
                            Name = "Lamp l3",
                            Price = 5000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 4,
                            Color = "Green",
                            Description = "Elegant lamp",
                            ImageUrl = "/images/l4.jpg",
                            IsTrending = false,
                            Name = "Lamp l4",
                            Price = 5500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 4,
                            Color = "Grey",
                            Description = "Modern floor lamp",
                            ImageUrl = "/images/l5.jpg",
                            IsTrending = false,
                            Name = "Lamp l5",
                            Price = 6000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 4,
                            Color = "Gold",
                            Description = "Stylish lamp",
                            ImageUrl = "/images/l6.jpg",
                            IsTrending = false,
                            Name = "Lamp l6",
                            Price = 5800m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 4,
                            Color = "White",
                            Description = "Wall lamp",
                            ImageUrl = "/images/l7.jpg",
                            IsTrending = false,
                            Name = "Lamp l7",
                            Price = 6200m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 4,
                            Color = "Beige",
                            Description = "Designer lamp",
                            ImageUrl = "/images/l8.jpg",
                            IsTrending = false,
                            Name = "Lamp l8",
                            Price = 6500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 4,
                            Color = "Black",
                            Description = "Luxury lamp",
                            ImageUrl = "/images/l9.jpg",
                            IsTrending = false,
                            Name = "Lamp l9",
                            Price = 7000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 4,
                            Color = "White",
                            Description = "Premium lamp",
                            ImageUrl = "/images/l10.jpg",
                            IsTrending = false,
                            Name = "Lamp l10",
                            Price = 7200m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 5,
                            Color = "White",
                            Description = "Decorative mirror",
                            ImageUrl = "/images/m1.jpg",
                            IsTrending = false,
                            Name = "Mirror m1",
                            Price = 5800m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 5,
                            Color = "Grey",
                            Description = "Modern mirror",
                            ImageUrl = "/images/m2.jpg",
                            IsTrending = false,
                            Name = "Mirror m2",
                            Price = 6000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 5,
                            Color = "White",
                            Description = "Artistic mirror",
                            ImageUrl = "/images/m3.jpg",
                            IsTrending = false,
                            Name = "Mirror m3",
                            Price = 6500m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 5,
                            Color = "Pink",
                            Description = "Round mirror",
                            ImageUrl = "/images/m4.jpg",
                            IsTrending = false,
                            Name = "Mirror m4",
                            Price = 6200m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 5,
                            Color = "White",
                            Description = "Soft round mirror",
                            ImageUrl = "/images/m5.jpg",
                            IsTrending = false,
                            Name = "Mirror m5",
                            Price = 7000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 5,
                            Color = "White",
                            Description = "Tall mirror",
                            ImageUrl = "/images/m6.jpg",
                            IsTrending = false,
                            Name = "Mirror m6",
                            Price = 7500m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 5,
                            Color = "Black",
                            Description = "Full-length mirror",
                            ImageUrl = "/images/m7.jpg",
                            IsTrending = false,
                            Name = "Mirror m7",
                            Price = 7800m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 5,
                            Color = "Green",
                            Description = "Luxury mirror",
                            ImageUrl = "/images/m8.jpg",
                            IsTrending = false,
                            Name = "Mirror m8",
                            Price = 8200m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 6,
                            Color = "Gold",
                            Description = "Decor item",
                            ImageUrl = "/images/de1.jpg",
                            IsTrending = false,
                            Name = "Decor de1",
                            Price = 3000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 6,
                            Color = "Beige",
                            Description = "Elegant decor",
                            ImageUrl = "/images/de2.jpg",
                            IsTrending = false,
                            Name = "Decor de2",
                            Price = 3500m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 6,
                            Color = "Gold",
                            Description = "Modern decor",
                            ImageUrl = "/images/de3.jpg",
                            IsTrending = false,
                            Name = "Decor de3",
                            Price = 3800m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 6,
                            Color = "Green",
                            Description = "Stylish decor",
                            ImageUrl = "/images/de4.jpg",
                            IsTrending = false,
                            Name = "Decor de4",
                            Price = 3600m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 6,
                            Color = "Gold",
                            Description = "Premium decor",
                            ImageUrl = "/images/de5.jpg",
                            IsTrending = false,
                            Name = "Decor de5",
                            Price = 4000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 6,
                            Color = "Cream",
                            Description = "Vase decor",
                            ImageUrl = "/images/de6.jpg",
                            IsTrending = false,
                            Name = "Decor de6",
                            Price = 4200m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 6,
                            Color = "Black",
                            Description = "Black decor set",
                            ImageUrl = "/images/de7.jpg",
                            IsTrending = false,
                            Name = "Decor de7",
                            Price = 3800m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 6,
                            Color = "Brown",
                            Description = "Wood decor",
                            ImageUrl = "/images/de8.jpg",
                            IsTrending = false,
                            Name = "Decor de8",
                            Price = 4500m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 6,
                            Color = "Silver",
                            Description = "Silver vase",
                            ImageUrl = "/images/de9.jpg",
                            IsTrending = false,
                            Name = "Decor de9",
                            Price = 4800m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 6,
                            Color = "Gold",
                            Description = "Elegant decor item",
                            ImageUrl = "/images/de10.jpg",
                            IsTrending = false,
                            Name = "Decor de10",
                            Price = 5000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 7,
                            Color = "Beige",
                            Description = "Round dining table",
                            ImageUrl = "/images/d1.jpg",
                            IsTrending = false,
                            Name = "Dining Table d1",
                            Price = 18000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 7,
                            Color = "Brown",
                            Description = "Wood dining table",
                            ImageUrl = "/images/d2.jpg",
                            IsTrending = false,
                            Name = "Dining Table d2",
                            Price = 20000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 7,
                            Color = "White",
                            Description = "Modern dining table",
                            ImageUrl = "/images/d3.jpg",
                            IsTrending = false,
                            Name = "Dining Table d3",
                            Price = 21000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 7,
                            Color = "Grey",
                            Description = "Classic dining table",
                            ImageUrl = "/images/d4.jpg",
                            IsTrending = false,
                            Name = "Dining Table d4",
                            Price = 22000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 7,
                            Color = "White",
                            Description = "Compact dining table",
                            ImageUrl = "/images/d5.jpg",
                            IsTrending = false,
                            Name = "Dining Table d5",
                            Price = 19000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 7,
                            Color = "Black",
                            Description = "Designer dining table",
                            ImageUrl = "/images/d6.jpg",
                            IsTrending = false,
                            Name = "Dining Table d6",
                            Price = 24000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 7,
                            Color = "Beige",
                            Description = "Stylish dining table",
                            ImageUrl = "/images/d7.jpg",
                            IsTrending = false,
                            Name = "Dining Table d7",
                            Price = 23000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 135,
                            CategoryId = 7,
                            Color = "Brown",
                            Description = "Wood table",
                            ImageUrl = "/images/d8.jpg",
                            IsTrending = false,
                            Name = "Dining Table d8",
                            Price = 21000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 136,
                            CategoryId = 7,
                            Color = "Silver",
                            Description = "Glass dining table",
                            ImageUrl = "/images/d9.jpg",
                            IsTrending = false,
                            Name = "Dining Table d9",
                            Price = 26000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 137,
                            CategoryId = 7,
                            Color = "White",
                            Description = "Elegant table",
                            ImageUrl = "/images/d10.jpg",
                            IsTrending = false,
                            Name = "Dining Table d10",
                            Price = 25000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 138,
                            CategoryId = 7,
                            Color = "Gold",
                            Description = "Luxury dining table",
                            ImageUrl = "/images/d11.jpg",
                            IsTrending = false,
                            Name = "Dining Table d11",
                            Price = 30000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 139,
                            CategoryId = 7,
                            Color = "Grey",
                            Description = "Artistic table",
                            ImageUrl = "/images/d12.jpg",
                            IsTrending = false,
                            Name = "Dining Table d12",
                            Price = 27000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 140,
                            CategoryId = 8,
                            Color = "White",
                            Description = "Round table",
                            ImageUrl = "/images/t1.jpg",
                            IsTrending = false,
                            Name = "Table t1",
                            Price = 9000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 141,
                            CategoryId = 8,
                            Color = "Beige",
                            Description = "Modern table",
                            ImageUrl = "/images/t2.jpg",
                            IsTrending = false,
                            Name = "Table t2",
                            Price = 9500m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 142,
                            CategoryId = 8,
                            Color = "Brown",
                            Description = "Wood table",
                            ImageUrl = "/images/t3.jpg",
                            IsTrending = false,
                            Name = "Table t3",
                            Price = 9800m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 143,
                            CategoryId = 8,
                            Color = "White",
                            Description = "Classic table",
                            ImageUrl = "/images/t4.jpg",
                            IsTrending = false,
                            Name = "Table t4",
                            Price = 10000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 144,
                            CategoryId = 8,
                            Color = "Grey",
                            Description = "Decor table",
                            ImageUrl = "/images/t5.jpg",
                            IsTrending = false,
                            Name = "Table t5",
                            Price = 10200m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 145,
                            CategoryId = 8,
                            Color = "White",
                            Description = "Side table",
                            ImageUrl = "/images/t6.jpg",
                            IsTrending = false,
                            Name = "Table t6",
                            Price = 11000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 146,
                            CategoryId = 8,
                            Color = "Brown",
                            Description = "Center table",
                            ImageUrl = "/images/t7.jpg",
                            IsTrending = false,
                            Name = "Table t7",
                            Price = 12000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 147,
                            CategoryId = 8,
                            Color = "White",
                            Description = "Premium table",
                            ImageUrl = "/images/t8.jpg",
                            IsTrending = false,
                            Name = "Table t8",
                            Price = 13000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 148,
                            CategoryId = 8,
                            Color = "Black",
                            Description = "Luxury table",
                            ImageUrl = "/images/t9.jpg",
                            IsTrending = false,
                            Name = "Table t9",
                            Price = 15000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 149,
                            CategoryId = 8,
                            Color = "White",
                            Description = "Coffee table",
                            ImageUrl = "/images/t10.jpg",
                            IsTrending = false,
                            Name = "Table t10",
                            Price = 14000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 150,
                            CategoryId = 8,
                            Color = "Brown",
                            Description = "Wood coffee table",
                            ImageUrl = "/images/t11.jpg",
                            IsTrending = false,
                            Name = "Table t11",
                            Price = 13500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 151,
                            CategoryId = 8,
                            Color = "Gold",
                            Description = "Round center table",
                            ImageUrl = "/images/t12.jpg",
                            IsTrending = false,
                            Name = "Table t12",
                            Price = 16000m,
                            Stock = 2
                        });
                });

            modelBuilder.Entity("website.Models.Product", b =>
                {
                    b.HasOne("website.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
